---
title: "Draft"
author: "Spencer Cook"
date: "April 25, 2020"
output: html_document
---

```{r}
# Setup
library(tidyverse)
library(ggplot2)
```

```{r}
# Read in the data
tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')

cost_of_living <- read_csv('data/cost_of_living.csv')
```


#Exploring Salary Potential

Do stem majors end up making more?
```{r}
ggplot(aes(stem_percent, mid_career_pay), data = salary_potential) +
  geom_point()
```

Do stem majors say that they make the world better?
```{r}
ggplot(aes(stem_percent, make_world_better_percent), data = salary_potential) +
  geom_point()
```



Does high tuition pay off?
```{r}
# Combine the salary and tuition tables
tuition_salary <- salary_potential %>%
  left_join(tuition_cost, by = "name")

# Remove 2 year degrees
tuition_salary %>%
  filter(degree_length != '2 year') %>%
  ggplot() +
  geom_point(aes(out_of_state_tuition, early_career_pay), data = tuition_salary)
```

same graph again but visualize by cost of living

```{r}
# add in cost of living based on state
# make this in tableau
salary_col <- tuition_salary %>%
  left_join(cost_of_living, by = c('state' = 'State'))

ggplot() +
  geom_point(aes(out_of_state_tuition, early_career_pay, col = cost_index), data = salary_col) +
  scale_color_gradient(low = "#000099", high = "#CC0000")
```



# Lets look at how much tuition prices are raising

```{r}
ggplot(data = historical_tuition) +
  geom_point(aes(year, tuition_cost))
```


